name: nakadi-client
version: '0.2.0.1'
synopsis: Client library for the Nakadi Event Broker
description: This package implements a client library for interacting
             with the Nakadi event broker system developed by Zalando.
category: Network
author: Moritz Schulte
maintainer: mtesseract@silverratio.net
copyright: (c) 2017 Moritz Schulte
license: BSD3
github: mtesseract/nakadi-haskell
extra-source-files:
- README.md
default-extensions:
- NoImplicitPrelude
- OverloadedStrings
- DuplicateRecordFields
ghc-options:
- -Wall
- -fno-warn-type-defaults
dependencies:
- base >=4.7 && <5
- conduit
- conduit-extra
- conduit-combinators
- iso8601-time
- bytestring
- containers
- vector
- hashable
- aeson
- monad-logger
- text
- lens
- http-types
- http-client
- http-client-tls
- http-conduit
- resourcet
- uuid
- mtl
- transformers
- scientific
- safe-exceptions
- unordered-containers
- time
- split
- aeson-casing
- tasty
- template-haskell
- retry
library:
  source-dirs: src
  exposed-modules:
  - Network.Nakadi
  - Network.Nakadi.Config
  - Network.Nakadi.EventTypes
  - Network.Nakadi.EventTypes.CursorDistances
  - Network.Nakadi.EventTypes.CursorsLag
  - Network.Nakadi.EventTypes.Events
  - Network.Nakadi.EventTypes.EventType
  - Network.Nakadi.EventTypes.Partitions
  - Network.Nakadi.EventTypes.Schemas
  - Network.Nakadi.EventTypes.ShiftedCursors
  - Network.Nakadi.Subscriptions
  - Network.Nakadi.Subscriptions.Cursors
  - Network.Nakadi.Subscriptions.Events
  - Network.Nakadi.Subscriptions.Stats
  - Network.Nakadi.Subscriptions.Subscription
  - Network.Nakadi.Types
  - Network.Nakadi.Types.Config
  - Network.Nakadi.Types.Exceptions
  - Network.Nakadi.Types.Logger
  - Network.Nakadi.Types.Problem
  - Network.Nakadi.Types.Service
  - Network.Nakadi.Types.Subscription
  - Network.Nakadi.Registry
  - Network.Nakadi.Lenses
tests:
  nakadi-client-test-suite:
    main: Tests.hs
    source-dirs: tests
    ghc-options:
    - -Wall -fno-warn-type-defaults
    dependencies:
    - base
    - classy-prelude
    - nakadi-client
    - tasty
    - tasty-hunit
    - http-client
    - http-conduit
    - aeson
    - lens-aeson
    - text
    - say
    - random
    - async
    - retry
