name: nakadi-client
version: '0.5.0.1'
synopsis: Client library for the Nakadi Event Broker
description: This package implements a client library for interacting
             with the Nakadi event broker system developed by Zalando.
category: Network
author: Moritz Clasmeier
maintainer: mtesseract@silverratio.net
copyright: (c) 2017, 2018 Moritz Clasmeier
license: BSD3
github: mtesseract/nakadi-haskell
extra-source-files:
- README.md
- AUTHORS.md
- .gitignore
default-extensions:
- NoImplicitPrelude
- OverloadedStrings
- DuplicateRecordFields
flags:
  devel:
    manual: true
    default: false
when:
- condition: flag(devel)
  then:
    ghc-options:
    - -Wall
    - -fno-warn-type-defaults
    - -Werror
  else:
    ghc-options:
    - -Wall
    - -fno-warn-type-defaults
dependencies:
- base >=4.7 && <5
- monad-control
- transformers-base
- conduit >= 1.3.0
- conduit-extra
- iso8601-time
- bytestring
- containers
- vector
- hashable
- aeson
- monad-logger
- text
- lens
- http-types
- http-client
- http-client-tls
- http-conduit
- resourcet
- uuid
- mtl
- transformers
- scientific
- exceptions
- safe-exceptions
- unordered-containers
- time
- split
- aeson-casing
- template-haskell
- retry
- unliftio-core
- primitive
library:
  source-dirs: src
  exposed-modules:
  - Network.Nakadi
  - Network.Nakadi.Prelude
  - Network.Nakadi.Base
  - Network.Nakadi.Config
  - Network.Nakadi.EventTypes
  - Network.Nakadi.EventTypes.CursorDistances
  - Network.Nakadi.EventTypes.CursorsLag
  - Network.Nakadi.EventTypes.Events
  - Network.Nakadi.EventTypes.EventType
  - Network.Nakadi.EventTypes.Partitions
  - Network.Nakadi.EventTypes.Schemas
  - Network.Nakadi.EventTypes.ShiftedCursors
  - Network.Nakadi.Subscriptions
  - Network.Nakadi.Subscriptions.Cursors
  - Network.Nakadi.Subscriptions.Events
  - Network.Nakadi.Subscriptions.Stats
  - Network.Nakadi.Subscriptions.Subscription
  - Network.Nakadi.Types
  - Network.Nakadi.Types.Config
  - Network.Nakadi.Types.Exceptions
  - Network.Nakadi.Types.Logger
  - Network.Nakadi.Types.Problem
  - Network.Nakadi.Types.Service
  - Network.Nakadi.Registry
  - Network.Nakadi.Lenses
  - Network.Nakadi.Internal.Http
  - Network.Nakadi.Internal.Retry
  - Network.Nakadi.HttpBackendIO
tests:
  nakadi-client-test-suite:
    main: Tests.hs
    source-dirs: tests
    ghc-options:
    - -Wall -fno-warn-type-defaults
    dependencies:
    - base
    - classy-prelude
    - nakadi-client
    - tasty
    - tasty-hunit
    - http-client
    - http-types
    - http-conduit
    - aeson
    - lens-aeson
    - text
    - say
    - random
    - async
    - retry
    - stm
    - stm-chans
    - stm-conduit
    - warp
    - wai
    - tasty
    - lifted-async
    - unliftio
    - monad-logger
    - fast-logger
